time_sec = int(input('введите время в секундах '))
hour = int(time_sec/3600)
min = int((time_sec-(hour*3600))/60)
sec = time_sec-(hour*3600)-(min*60)
time_str='{}:{}:{}'.format(hour,min,sec)
print(time_str)